#!/bin/bash

# Consistency audit — enforces the single-source constitution.
# 在主題根目錄執行：bash audit-consistency.sh
# 檢查 1: block CSS / templates 內不得出現硬編碼 hex 色與任意 px 值。
# 檢查 2: templates 內不得出現 inline style。
# 檢查 3: 元件清單中列出但沒有對應 block 的項目。
# 結果輸出至 design/consistency-report.md，全部通過時 exit 0。

set -u

REPORT="design/consistency-report.md"
mkdir -p design
FAIL=0

{
	echo "# Consistency Report"
	echo ""
	echo "Generated by wp-block-theme-pipeline audit."
	echo ""
} > "$REPORT"

section() {
	echo "" >> "$REPORT"
	echo "## $1" >> "$REPORT"
	echo "" >> "$REPORT"
}

# 1. 硬編碼 hex 色（block CSS 與 templates/patterns）。
section "Hard-coded hex colors (must be 0)"
HEX=$(rg -n --no-heading '#[0-9a-fA-F]{3,8}\b' blocks templates patterns 2>/dev/null \
	| rg -v 'theme\.json|\.map$|build/')
if [ -n "$HEX" ]; then
	FAIL=1
	echo '```' >> "$REPORT"
	echo "$HEX" >> "$REPORT"
	echo '```' >> "$REPORT"
	echo "❌ FAIL — use var(--wp--preset--color--*) tokens instead." >> "$REPORT"
else
	echo "✅ PASS" >> "$REPORT"
fi

# 2. 硬編碼 px（允許 0px 與 1px 細邊框；media query 行豁免）。
section "Hard-coded px values (must be 0, except 0px/1px and media queries)"
PX=$(rg -n --no-heading '\b([2-9]|[1-9][0-9]+)px\b' blocks templates patterns 2>/dev/null \
	| rg -v '@media|\.map$|build/|theme\.json')
if [ -n "$PX" ]; then
	FAIL=1
	echo '```' >> "$REPORT"
	echo "$PX" >> "$REPORT"
	echo '```' >> "$REPORT"
	echo "❌ FAIL — use var(--wp--preset--spacing--*) / font-size presets instead." >> "$REPORT"
else
	echo "✅ PASS" >> "$REPORT"
fi

# 3. templates / patterns 內的 inline style。
section "Inline styles in templates/patterns (must be 0)"
INLINE=$(rg -n --no-heading 'style="' templates patterns 2>/dev/null \
	| rg -v 'wp-block|build/')
if [ -n "$INLINE" ]; then
	FAIL=1
	echo '```' >> "$REPORT"
	echo "$INLINE" >> "$REPORT"
	echo '```' >> "$REPORT"
	echo "❌ FAIL — pages reference blocks; they never carry styles." >> "$REPORT"
else
	echo "✅ PASS" >> "$REPORT"
fi

# 4. 元件清單 vs 實作 block 的落差。
section "Inventory components without a block (informational)"
if [ -f "design/component-inventory.md" ] && [ -d "blocks" ]; then
	MISSING=""
	while IFS= read -r slug; do
		if [ ! -d "blocks/$slug" ]; then
			MISSING="$MISSING- $slug\n"
		fi
	done < <(rg -o '^\s*[-*]\s*`([a-z0-9-]+)`' -r '$1' design/component-inventory.md 2>/dev/null | sort -u)
	if [ -n "$MISSING" ]; then
		printf "%b" "$MISSING" >> "$REPORT"
		echo "⚠️  Listed in the inventory but not implemented — user decides." >> "$REPORT"
	else
		echo "✅ All inventory components have a block." >> "$REPORT"
	fi
else
	echo "Skipped — design/component-inventory.md or blocks/ not found." >> "$REPORT"
fi

echo "" >> "$REPORT"
if [ $FAIL -eq 0 ]; then
	echo "**Result: ✅ ALL PASS**" >> "$REPORT"
	echo "✅ Consistency audit passed. Report: $REPORT"
else
	echo "**Result: ❌ FAILURES FOUND — fix at the single source, never in pages.**" >> "$REPORT"
	echo "❌ Consistency audit failed. Report: $REPORT"
fi
exit $FAIL
